// <auto-generated />
using System;
using CodeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260505162107_ModelChange2")]
    partial class ModelChange2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeApp.Models.Entities.Food", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CodeApp.Models.Entities.FoodProducer", b =>
                {
                    b.Property<int>("foodId")
                        .HasColumnType("integer");

                    b.Property<int>("producerId")
                        .HasColumnType("integer");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.HasKey("foodId", "producerId");

                    b.HasIndex("producerId");

                    b.ToTable("FoodProducers");
                });

            modelBuilder.Entity("CodeApp.Models.Entities.Producer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("CodeApp.Models.Entities.FoodProducer", b =>
                {
                    b.HasOne("CodeApp.Models.Entities.Food", "food")
                        .WithMany("foodProducers")
                        .HasForeignKey("foodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeApp.Models.Entities.Producer", "producer")
                        .WithMany("foodProducers")
                        .HasForeignKey("producerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("food");

                    b.Navigation("producer");
                });

            modelBuilder.Entity("CodeApp.Models.Entities.Food", b =>
                {
                    b.Navigation("foodProducers");
                });

            modelBuilder.Entity("CodeApp.Models.Entities.Producer", b =>
                {
                    b.Navigation("foodProducers");
                });
#pragma warning restore 612, 618
        }
    }
}
